vim.g.mapleader = " "
vim.g.laststatus = 3 -- global statusline

vim.o.shortmess = vim.o.shortmess .. "c"
vim.o.laststatus = 3 -- global statusline
vim.o.pumblend = 10 -- popup blend
vim.o.pumheight = 10 -- maximum number of entries in a popup
vim.o.scrolloff = 4  -- lines of context
vim.o.showcmd = true
vim.o.incsearch = true
vim.o.expandtab = true -- uses spaces instead of tabs
vim.o.tabstop = 4 -- number of spaces in tab
vim.o.shiftround = true -- round indent
vim.o.shiftwidth = 4 -- size of an indent
vim.o.softtabstop = 4
vim.o.smartcase = true -- don't ignore case with capitals
vim.o.ignorecase = true
vim.o.smartindent = true -- insert indents automatically
vim.o.updatetime = 200 -- save swap file and trigger CursorHold
vim.o.hlsearch = true
vim.o.termguicolors = true -- true color support
vim.o.expandtab = true
vim.o.showmode = false -- don't show the mode since we have a status line
vim.o.number = true -- line numbers
vim.o.relativenumber = true -- relative line numbers
vim.o.wrap = true -- enable line wrap
vim.o.signcolumn = "yes"
vim.o.background = "light"
