theme = "bogster"

[editor]
mouse = false
line-number = "relative"
auto-pairs = false

[editor.filepicker]
hidden = false

[lsp]
display-messages = true

[keys.normal]
"^" = "goto_line_start"
"$" = "goto_line_end"
G = "goto_last_line" 

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode