#!/usr/bin/env sh

spacebar -m config position             bottom
spacebar -m config height               26
spacebar -m config title                on
spacebar -m config spaces               on
spacebar -m config clock                on
spacebar -m config power                on
spacebar -m config padding_left         20
spacebar -m config padding_right        20
spacebar -m config spacing_left         25
spacebar -m config spacing_right        15
spacebar -m config text_font            "JetBrainsMono Nerd Font:Medium:11.0"
spacebar -m config icon_font            "Font Awesome 6 Free:Solid:11.0"

# horizon theme
# spacebar -m config background_color     0xff1c1e26
# spacebar -m config foreground_color     0xffd5d8da
# spacebar -m config space_icon_color     0xffb877db
# spacebar -m config power_icon_color     0xffd79921
# spacebar -m config battery_icon_color   0xffec6a88
# spacebar -m config dnd_icon_color       0xff458588
# spacebar -m config clock_icon_color     0xff21bfc2

# tokyodark
spacebar -m config background_color     0xff11121D
spacebar -m config foreground_color     0xffd5d8da
spacebar -m config space_icon_color     0xffb877db
spacebar -m config power_icon_color     0xffd79921
spacebar -m config battery_icon_color   0xffec6a88
spacebar -m config dnd_icon_color       0xff458588
spacebar -m config clock_icon_color     0xff21bfc2

spacebar -m config power_icon_strip      
spacebar -m config space_icon_strip     I II III IV V VI VII VIII IX X
spacebar -m config space_icon           
spacebar -m config clock_icon           
spacebar -m config dnd_icon             
spacebar -m config clock_format         "%m/%d/%y %r"

echo "spacebar configuration loaded.."
