#!/usr/bin/env sh

spacebar -m config position             bottom
spacebar -m config height               26
spacebar -m config title                on
spacebar -m config spaces               on
spacebar -m config clock                on
spacebar -m config power                on
spacebar -m config padding_left         20
spacebar -m config padding_right        20
spacebar -m config spacing_left         25
spacebar -m config spacing_right        15
spacebar -m config text_font            "JetBrainsMono Nerd Font:Bold:11.0"
spacebar -m config icon_font            "Font Awesome 6 Free:Solid:12.0"

# zenflesh theme colors
# spacebar -m config background_color     0xff1C1918
# spacebar -m config foreground_color     0xffB4BDC3
# spacebar -m config space_icon_color     0xff819B69
# spacebar -m config power_icon_color     0xffB77E64
# spacebar -m config battery_icon_color   0xffDE6E7C
# spacebar -m config dnd_icon_color       0xff6099C0
# spacebar -m config clock_icon_color     0xff66A5AD

# gruvbox medium colors
spacebar -m config background_color     0xff282828
spacebar -m config foreground_color     0xffebdbb2
spacebar -m config space_icon_color     0xff8ec07c
spacebar -m config power_icon_color     0xfffabd2f
spacebar -m config battery_icon_color   0xfffb4934
spacebar -m config dnd_icon_color       0xff458588
spacebar -m config clock_icon_color     0xfffe8019

spacebar -m config power_icon_strip      
spacebar -m config space_icon_strip     I II III IV V VI VII VIII IX X
spacebar -m config space_icon           
spacebar -m config clock_icon           
spacebar -m config dnd_icon             
spacebar -m config clock_format         "%m/%d/%y %r"

echo "spacebar configuration loaded.."
